apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ../../optional/console-plugin
- ../../optional/prometheus-ocp

patches:
  - path: clusterserviceversion_patch.yaml
    target:
      kind: ClusterServiceVersion
  - path: deployment_patch.yaml
    target:
      kind: Deployment
      name: controller-manager
  - path: auth_proxy_service_patch.yaml
    target:
      kind: Service
      name: controller-manager-metrics-service
